# 01 - Data Understanding

## Objective
Load and inspect all five raw CSV datasets. For each dataset, we report:
- Shape (rows, columns)
- Column names and data types
- Missing values
- Duplicate rows
- Possible ID columns
- Purpose in the project

**No merging or cleaning happens here — this is pure observation.**

---

In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 200)

DATA_PATH = "../data/raw"
print("Files in data/raw:")
for f in sorted(os.listdir(DATA_PATH)):
    print(f"  - {f}")

Files in data/raw:
  - employee_attrition.csv
  - essential_skills.csv
  - hr_performance_engagement.csv
  - occupation_data.csv
  - software_skills.csv

---
## Dataset 1: employee_attrition.csv
**Expected purpose:** Attrition prediction (one row per employee, target = Attrition)
---

In [2]:
df_attrition = pd.read_csv(f"{DATA_PATH}/employee_attrition.csv")

print("=== SHAPE ===")
print(f"Rows: {df_attrition.shape[0]}, Columns: {df_attrition.shape[1]}")
print()

print("=== COLUMN NAMES ===")
for i, col in enumerate(df_attrition.columns):
    print(f"  {i+1}. {col}")
print()

print("=== FIRST 5 ROWS ===")
df_attrition.head()

=== SHAPE ===
Rows: 1470, Columns: 35

=== COLUMN NAMES ===
  1. Age
  2. Attrition
  3. BusinessTravel
  4. DailyRate
  5. Department
  6. DistanceFromHome
  7. Education
  8. EducationField
  9. EmployeeCount
  10. EmployeeNumber
  11. EnvironmentSatisfaction
  12. Gender
  13. HourlyRate
  14. JobInvolvement
  15. JobLevel
  16. JobRole
  17. JobSatisfaction
  18. MaritalStatus
  19. MonthlyIncome
  20. MonthlyRate
  21. NumCompaniesWorked
  22. Over18
  23. OverTime
  24. PercentSalaryHike
  25. PerformanceRating
  26. RelationshipSatisfaction
  27. StandardHours
  28. StockOptionLevel
  29. TotalWorkingYears
  30. TrainingTimesLastYear
  31. WorkLifeBalance
  32. YearsAtCompany
  33. YearsInCurrentRole
  34. YearsSinceLastPromotion
  35. YearsWithCurrManager

=== FIRST 5 ROWS ===

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,8,Y,Yes,11,3,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,3,Male,61,2,2,Research Scientist,2,Married,5130,24907,1,Y,No,23,4,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,4,Male,92,2,1,Laboratory Technician,3,Single,2090,2396,6,Y,Yes,15,3,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,4,Female,56,3,1,Research Scientist,3,Married,2909,23159,1,Y,Yes,11,3,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,1,Male,40,3,1,Laboratory Technician,2,Married,3468,16632,9,Y,No,12,3,4,80,1,6,3,3,2,2,2,2

In [3]:
print("=== DATA INFO ===")
df_attrition.info()

=== DATA INFO ===
<class 'pandas.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   str
 2   BusinessTravel            1470 non-null   str
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   str
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   str
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   str
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   str
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   str
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   str
 22  OverTime                  1470 non-null   str
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), str(9)
memory usage: 510.8 KB

In [4]:
print("=== MISSING VALUES (sorted) ===")
missing = df_attrition.isnull().sum().sort_values(ascending=False)
print(missing[missing > 0] if missing.sum() > 0 else "No missing values found.")
print()
print(f"Total missing values: {df_attrition.isnull().sum().sum()}")

=== MISSING VALUES (sorted) ===
No missing values found.

Total missing values: 0

In [5]:
print("=== DUPLICATE ROWS ===")
dup_count = df_attrition.duplicated().sum()
print(f"Duplicate rows: {dup_count}")

=== DUPLICATE ROWS ===
Duplicate rows: 0

In [6]:
print("=== POSSIBLE ID COLUMNS ===")
id_cols = [c for c in df_attrition.columns if "id" in c.lower()]
print(f"Columns with 'id' in name: {id_cols}")
print()

# Check uniqueness of candidate ID columns
for col in id_cols:
    unique_count = df_attrition[col].nunique()
    total = len(df_attrition)
    status = "(UNIQUE)" if unique_count == total else "(NOT UNIQUE)"
    print(f"  {col}: {unique_count} unique values out of {total} rows {status}")

=== POSSIBLE ID COLUMNS ===
Columns with 'id' in name: []

In [7]:
print("=== DATA TYPES ===")
print()
num_cols = df_attrition.select_dtypes(include=[np.number]).columns.tolist()
cat_cols = df_attrition.select_dtypes(include=["object", "category", "str"]).columns.tolist()

print(f"Numerical columns ({len(num_cols)}):")
for c in num_cols:
    print(f"  - {c}")
print()
print(f"Categorical/text columns ({len(cat_cols)}):")
for c in cat_cols:
    print(f"  - {c}")

=== DATA TYPES ===

Numerical columns (26):
  - Age
  - DailyRate
  - DistanceFromHome
  - Education
  - EmployeeCount
  - EmployeeNumber
  - EnvironmentSatisfaction
  - HourlyRate
  - JobInvolvement
  - JobLevel
  - JobSatisfaction
  - MonthlyIncome
  - MonthlyRate
  - NumCompaniesWorked
  - PercentSalaryHike
  - PerformanceRating
  - RelationshipSatisfaction
  - StandardHours
  - StockOptionLevel
  - TotalWorkingYears
  - TrainingTimesLastYear
  - WorkLifeBalance
  - YearsAtCompany
  - YearsInCurrentRole
  - YearsSinceLastPromotion
  - YearsWithCurrManager

Categorical/text columns (9):
  - Attrition
  - BusinessTravel
  - Department
  - EducationField
  - Gender
  - JobRole
  - MaritalStatus
  - Over18
  - OverTime

### Special: Attrition Target Distribution
The professor specifically requires checking the balance of the Attrition target variable.
---

In [8]:
print("=== ATTRITION TARGET DISTRIBUTION ===")
print()
print("Value counts:")
print(df_attrition["Attrition"].value_counts())
print()
print("Percentage distribution:")
attrition_pct = df_attrition["Attrition"].value_counts(normalize=True) * 100
print(attrition_pct.round(2))
print()

yes_count = df_attrition["Attrition"].value_counts().get("Yes", 0)
no_count = df_attrition["Attrition"].value_counts().get("No", 0)
total = len(df_attrition)
print(f"Summary: Yes={yes_count} ({yes_count/total*100:.1f}%), No={no_count} ({no_count/total*100:.1f}%)")
print()
if yes_count / total < 0.2:
    print("WARNING: Attrition is imbalanced (< 20% Yes). Models will need stratification.")

=== ATTRITION TARGET DISTRIBUTION ===

Value counts:
Attrition
No     1233
Yes     237
Name: count, dtype: int64

Percentage distribution:
Attrition
No     83.88
Yes    16.12
Name: proportion, dtype: float64

Summary: Yes=237 (16.1%), No=1233 (83.9%)

WARNING: Attrition is imbalanced (< 20% Yes). Models will need stratification.

---
## Dataset 2: hr_performance_engagement.csv
**Expected purpose:** Engagement/performance analytics
---

In [9]:
df_engagement = pd.read_csv(f"{DATA_PATH}/hr_performance_engagement.csv")

print("=== SHAPE ===")
print(f"Rows: {df_engagement.shape[0]}, Columns: {df_engagement.shape[1]}")
print()

print("=== COLUMN NAMES ===")
for i, col in enumerate(df_engagement.columns):
    print(f"  {i+1}. {col}")
print()

print("=== FIRST 5 ROWS ===")
df_engagement.head()

=== SHAPE ===
Rows: 2845, Columns: 28

=== COLUMN NAMES ===
  1. Employee ID
  2. StartDate
  3. Title
  4. BusinessUnit
  5. EmployeeStatus
  6. EmployeeType
  7. PayZone
  8. EmployeeClassificationType
  9. DepartmentType
  10. Division
  11. DOB
  12. State
  13. GenderCode
  14. RaceDesc
  15. MaritalDesc
  16. Performance Score
  17. Current Employee Rating
  18. Survey Date
  19. Engagement Score
  20. Satisfaction Score
  21. Work-Life Balance Score
  22. Training Date
  23. Training Program Name
  24. Training Type
  25. Training Outcome
  26. Training Duration(Days)
  27. Training Cost
  28. Age

=== FIRST 5 ROWS ===

,Employee ID,StartDate,Title,BusinessUnit,EmployeeStatus,EmployeeType,PayZone,EmployeeClassificationType,DepartmentType,Division,DOB,State,GenderCode,RaceDesc,MaritalDesc,Performance Score,Current Employee Rating,Survey Date,Engagement Score,Satisfaction Score,Work-Life Balance Score,Training Date,Training Program Name,Training Type,Training Outcome,Training Duration(Days),Training Cost,Age
0,3427,20-Sep-19,Production Technician I,CCDR,Active,Contract,Zone C,Temporary,Production,Finance & Accounting,07-10-1969,MA,Female,White,Widowed,Fully Meets,4,14-01-2023,1,2,3,15-Jul-23,Leadership Development,Internal,Failed,2,606.11,50
1,3428,11-Feb-23,Production Technician I,EW,Active,Contract,Zone A,Part-Time,Production,Aerial,30-08-1965,MA,Male,Hispanic,Widowed,Fully Meets,3,09-09-2022,2,1,5,12-Sep-22,Customer Service,External,Incomplete,4,673.02,58
2,3429,10-Dec-18,Area Sales Manager,PL,Active,Full-Time,Zone B,Part-Time,Sales,General - Sga,06-10-1991,MA,Male,Hispanic,Widowed,Fully Meets,4,27-05-2023,1,2,1,13-Aug-22,Leadership Development,External,Failed,2,413.28,27
3,3430,21-Jun-21,Area Sales Manager,CCDR,Active,Contract,Zone A,Full-Time,Sales,Finance & Accounting,04-04-1998,ND,Male,Other,Single,Fully Meets,2,16-06-2023,5,5,4,15-Dec-22,Project Management,External,Completed,3,663.78,23
4,3431,29-Jun-19,Area Sales Manager,TNS,Active,Contract,Zone A,Temporary,Sales,General - Con,29-08-1969,FL,Female,Other,Married,Fully Meets,3,25-11-2022,2,5,3,13-Jul-23,Technical Skills,External,Failed,5,399.03,50

In [10]:
print("=== DATA INFO ===")
df_engagement.info()

=== DATA INFO ===
<class 'pandas.DataFrame'>
RangeIndex: 2845 entries, 0 to 2844
Data columns (total 28 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Employee ID                 2845 non-null   int64
 1   StartDate                   2845 non-null   str
 2   Title                       2845 non-null   str
 3   BusinessUnit                2845 non-null   str
 4   EmployeeStatus              2845 non-null   str
 5   EmployeeType                2845 non-null   str
 6   PayZone                     2845 non-null   str
 7   EmployeeClassificationType  2845 non-null   str
 8   DepartmentType              2845 non-null   str
 9   Division                    2845 non-null   str
 10  DOB                         2845 non-null   str
 11  State                       2845 non-null   str
 12  GenderCode                  2845 non-null   str
 13  RaceDesc                    2845 non-null   str
 14  MaritalDesc                 2845 non-null   str
 15  Performance Score           2845 non-null   str
 16  Current Employee Rating     2845 non-null   int64
 17  Survey Date                 2845 non-null   str
 18  Engagement Score            2845 non-null   int64
 19  Satisfaction Score          2845 non-null   int64
 20  Work-Life Balance Score     2845 non-null   int64
 21  Training Date               2845 non-null   str
 22  Training Program Name       2845 non-null   str
 23  Training Type               2845 non-null   str
 24  Training Outcome            2845 non-null   str
 25  Training Duration(Days)     2845 non-null   int64
 26  Training Cost               2845 non-null   float64
 27  Age                         2845 non-null   int64
dtypes: float64(1), int64(7), str(20)
memory usage: 1.1 MB

In [11]:
print("=== MISSING VALUES (sorted) ===")
missing = df_engagement.isnull().sum().sort_values(ascending=False)
print(missing[missing > 0] if missing.sum() > 0 else "No missing values found.")
print()
print(f"Total missing values: {df_engagement.isnull().sum().sum()}")

=== MISSING VALUES (sorted) ===
No missing values found.

Total missing values: 0

In [12]:
print("=== DUPLICATE ROWS ===")
dup_count = df_engagement.duplicated().sum()
print(f"Duplicate rows: {dup_count}")

=== DUPLICATE ROWS ===
Duplicate rows: 0

In [13]:
print("=== POSSIBLE ID COLUMNS ===")
id_cols = [c for c in df_engagement.columns if "id" in c.lower() or "employee" in c.lower()]
print(f"Columns with 'id' or 'employee' in name: {id_cols}")
print()

for col in id_cols:
    unique_count = df_engagement[col].nunique()
    total = len(df_engagement)
    status = "(UNIQUE)" if unique_count == total else "(NOT UNIQUE)"
    print(f"  {col}: {unique_count} unique values out of {total} rows {status}")

=== POSSIBLE ID COLUMNS ===
Columns with 'id' or 'employee' in name: ['Employee ID', 'EmployeeStatus', 'EmployeeType', 'EmployeeClassificationType', 'Current Employee Rating']

  Employee ID: 2845 unique values out of 2845 rows (UNIQUE)
  EmployeeStatus: 2 unique values out of 2845 rows (NOT UNIQUE)
  EmployeeType: 3 unique values out of 2845 rows (NOT UNIQUE)
  EmployeeClassificationType: 3 unique values out of 2845 rows (NOT UNIQUE)
  Current Employee Rating: 5 unique values out of 2845 rows (NOT UNIQUE)

In [14]:
print("=== DATA TYPES ===")
print()
num_cols = df_engagement.select_dtypes(include=[np.number]).columns.tolist()
cat_cols = df_engagement.select_dtypes(include=["object", "category", "str"]).columns.tolist()

print(f"Numerical columns ({len(num_cols)}):")
for c in num_cols:
    print(f"  - {c}")
print()
print(f"Categorical/text columns ({len(cat_cols)}):")
for c in cat_cols:
    print(f"  - {c}")

=== DATA TYPES ===

Numerical columns (8):
  - Employee ID
  - Current Employee Rating
  - Engagement Score
  - Satisfaction Score
  - Work-Life Balance Score
  - Training Duration(Days)
  - Training Cost
  - Age

Categorical/text columns (20):
  - StartDate
  - Title
  - BusinessUnit
  - EmployeeStatus
  - EmployeeType
  - PayZone
  - EmployeeClassificationType
  - DepartmentType
  - Division
  - DOB
  - State
  - GenderCode
  - RaceDesc
  - MaritalDesc
  - Performance Score
  - Survey Date
  - Training Date
  - Training Program Name
  - Training Type
  - Training Outcome

---
## Dataset 3: occupation_data.csv
**Expected purpose:** Occupation/role master reference table
---

In [15]:
df_occupation = pd.read_csv(f"{DATA_PATH}/occupation_data.csv")

print("=== SHAPE ===")
print(f"Rows: {df_occupation.shape[0]}, Columns: {df_occupation.shape[1]}")
print()

print("=== COLUMN NAMES ===")
for i, col in enumerate(df_occupation.columns):
    print(f"  {i+1}. {col}")
print()

print("=== FIRST 5 ROWS ===")
df_occupation.head()

=== SHAPE ===

Rows: 1016, Columns: 3

=== COLUMN NAMES ===
  1. O*NET-SOC Code
  2. Title
  3. Description

=== FIRST 5 ROWS ===

  O*NET-SOC Code                                Title                                        Description
0     11-1011.00                     Chief Executives  Determine and formulate policies and provide o...
1     11-1011.03        Chief Sustainability Officers  Communicate and coordinate with management, sh...
2     11-1021.00      General and Operations Managers  Plan, direct, or coordinate the operations of ...
3     11-1031.00                          Legislators  Develop, introduce, or enact laws and statutes...
4     11-2011.00  Advertising and Promotions Managers  Plan, direct, or coordinate advertising polici...

In [16]:
print("=== DATA INFO ===")
df_occupation.info()

=== DATA INFO ===
<class 'pandas.DataFrame'>
RangeIndex: 1016 entries, 0 to 1015
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   O*NET-SOC Code  1016 non-null   str
 1   Title           1016 non-null   str
 2   Description     1016 non-null   str
dtypes: str(3)
memory usage: 279.5 KB

In [17]:
print("=== MISSING VALUES (sorted) ===")
missing = df_occupation.isnull().sum().sort_values(ascending=False)
print(missing[missing > 0] if missing.sum() > 0 else "No missing values found.")
print()
print(f"Total missing values: {df_occupation.isnull().sum().sum()}")

=== MISSING VALUES (sorted) ===
No missing values found.

Total missing values: 0

In [18]:
print("=== DUPLICATE ROWS ===")
dup_count = df_occupation.duplicated().sum()
print(f"Duplicate rows: {dup_count}")

=== DUPLICATE ROWS ===

Duplicate rows: 0

In [19]:
print("=== POSSIBLE ID COLUMNS ===")
id_cols = [c for c in df_occupation.columns if "id" in c.lower() or "code" in c.lower()]
print(f"Columns with 'id' or 'code' in name: {id_cols}")
print()

for col in id_cols:
    unique_count = df_occupation[col].nunique()
    total = len(df_occupation)
    status = "(UNIQUE)" if unique_count == total else "(NOT UNIQUE)"
    print(f"  {col}: {unique_count} unique values out of {total} rows {status}")

=== POSSIBLE ID COLUMNS ===
Columns with 'id' or 'code' in name: ['O*NET-SOC Code']

  O*NET-SOC Code: 1016 unique values out of 1016 rows (UNIQUE)

---
## Dataset 4: essential_skills.csv
**Expected purpose:** Essential skills required by roles
---

In [20]:
df_essential = pd.read_csv(f"{DATA_PATH}/essential_skills.csv")

print("=== SHAPE ===")
print(f"Rows: {df_essential.shape[0]}, Columns: {df_essential.shape[1]}")
print()

print("=== COLUMN NAMES ===")
for i, col in enumerate(df_essential.columns):
    print(f"  {i+1}. {col}")
print()

print("=== FIRST 5 ROWS ===")
df_essential.head()

=== SHAPE ===

Rows: 18200, Columns: 15

=== COLUMN NAMES ===
  1. O*NET-SOC Code
  2. Title
  3. Element ID
  4. Element Name
  5. Scale ID
  6. Scale Name
  7. Data Value
  8. N
  9. Standard Error
  10. Lower CI Bound
  11. Upper CI Bound
  12. Recommend Suppress
  13. Not Relevant
  14. Date
  15. Domain Source

=== FIRST 5 ROWS ===

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Not Relevant,Date,Domain Source
0,11-1011.00,Chief Executives,2.A.1.a,Reading Comprehension,IM,Importance,4.12,8,0.1250,3.8800,4.3700,N,NaN,08/2023,Analyst
1,11-1011.00,Chief Executives,2.A.1.a,Reading Comprehension,LV,Level,4.62,8,0.1830,4.2664,4.9836,N,N,08/2023,Analyst
2,11-1011.00,Chief Executives,2.A.1.b,Active Listening,IM,Importance,4.00,8,0.0000,4.0000,4.0000,N,NaN,08/2023,Analyst
3,11-1011.00,Chief Executives,2.A.1.b,Active Listening,LV,Level,4.75,8,0.1637,4.4292,5.0708,N,N,08/2023,Analyst
4,11-1011.00,Chief Executives,2.A.1.c,Writing,IM,Importance,4.12,8,0.1250,3.8800,4.3700,N,NaN,08/2023,Analyst

In [21]:
print("=== DATA INFO ===")
df_essential.info()

=== DATA INFO ===
<class 'pandas.DataFrame'>
RangeIndex: 18200 entries, 0 to 18199
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   O*NET-SOC Code      18200 non-null  str
 1   Title               18200 non-null  str
 2   Element ID          18200 non-null  str
 3   Element Name        18200 non-null  str
 4   Scale ID            18200 non-null  str
 5   Scale Name          18200 non-null  str
 6   Data Value          18200 non-null  float64
 7   N                   18200 non-null  int64
 8   Standard Error      18200 non-null  float64
 9   Lower CI Bound      18200 non-null  float64
 10  Upper CI Bound      18200 non-null  float64
 11  Recommend Suppress  18200 non-null  str
 12  Not Relevant        9100 non-null   str
 13  Date                18200 non-null  str
 14  Domain Source       18200 non-null  str
dtypes: float64(4), int64(1), str(10)
memory usage: 3.6 MB

In [22]:
print("=== MISSING VALUES (sorted) ===")
missing = df_essential.isnull().sum().sort_values(ascending=False)
print(missing[missing > 0] if missing.sum() > 0 else "No missing values found.")
print()
print(f"Total missing values: {df_essential.isnull().sum().sum()}")

=== MISSING VALUES (sorted) ===
Not Relevant    9100
dtype: int64

Total missing values: 9100

In [23]:
print("=== DUPLICATE ROWS ===")
dup_count = df_essential.duplicated().sum()
print(f"Duplicate rows: {dup_count}")

=== DUPLICATE ROWS ===
Duplicate rows: 0

In [24]:
print("=== POSSIBLE ID COLUMNS ===")
id_cols = [c for c in df_essential.columns if "id" in c.lower() or "code" in c.lower()]
print(f"Columns with 'id' or 'code' in name: {id_cols}")
print()

for col in id_cols:
    unique_count = df_essential[col].nunique()
    total = len(df_essential)
    status = "(UNIQUE)" if unique_count == total else "(NOT UNIQUE)"
    print(f"  {col}: {unique_count} unique values out of {total} rows {status}")

=== POSSIBLE ID COLUMNS ===
Columns with 'id' or 'code' in name: ['O*NET-SOC Code', 'Element ID', 'Scale ID']

  O*NET-SOC Code: 910 unique values out of 18200 rows (NOT UNIQUE)
  Element ID: 10 unique values out of 18200 rows (NOT UNIQUE)
  Scale ID: 2 unique values out of 18200 rows (NOT UNIQUE)

In [25]:
print("=== DATA TYPES ===")
print()
num_cols = df_essential.select_dtypes(include=[np.number]).columns.tolist()
cat_cols = df_essential.select_dtypes(include=["object", "category", "str"]).columns.tolist()

print(f"Numerical columns ({len(num_cols)}):")
for c in num_cols:
    print(f"  - {c}")
print()
print(f"Categorical/text columns ({len(cat_cols)}):")
for c in cat_cols:
    print(f"  - {c}")

=== DATA TYPES ===

Numerical columns (5):
  - Data Value
  - N
  - Standard Error
  - Lower CI Bound
  - Upper CI Bound

Categorical/text columns (10):
  - O*NET-SOC Code
  - Title
  - Element ID
  - Element Name
  - Scale ID
  - Scale Name
  - Recommend Suppress
  - Not Relevant
  - Date
  - Domain Source

---
## Dataset 5: software_skills.csv
**Expected purpose:** Software/technology skills required by roles
---

In [26]:
df_software = pd.read_csv(f"{DATA_PATH}/software_skills.csv")

print("=== SHAPE ===")
print(f"Rows: {df_software.shape[0]}, Columns: {df_software.shape[1]}")
print()

print("=== COLUMN NAMES ===")
for i, col in enumerate(df_software.columns):
    print(f"  {i+1}. {col}")
print()

print("=== FIRST 5 ROWS ===")
df_software.head()

=== SHAPE ===
Rows: 31821, Columns: 7

=== COLUMN NAMES ===
  1. O*NET-SOC Code
  2. Title
  3. Workplace Example
  4. Element ID
  5. Element Name
  6. Hot Technology
  7. In Demand

=== FIRST 5 ROWS ===

  O*NET-SOC Code             Title                              Workplace Example Element ID                                   Element Name Hot Technology In Demand
0     11-1011.00  Chief Executives                                  Adobe Acrobat    2.E.5.b                   Document management software              Y         N
1     11-1011.00  Chief Executives                                AdSense Tracker    2.E.6.f    Data base user interface and query software              N         N
2     11-1011.00  Chief Executives                                 Atlassian JIRA    2.E.5.a                      Content workflow software              Y         N
3     11-1011.00  Chief Executives                    Blackbaud The Raiser's Edge    2.E.6.c  Customer relationship management CRM software              N         N
4     11-1011.00  Chief Executives  ComputerEase construction accounting software    2.E.2.a                            Accounting software              N         N

In [27]:
print("=== DATA INFO ===")
df_software.info()

=== DATA INFO ===
<class 'pandas.DataFrame'>
RangeIndex: 31821 entries, 0 to 31820
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   O*NET-SOC Code     31821 non-null  str
 1   Title              31821 non-null  str
 2   Workplace Example  31821 non-null  str
 3   Element ID         31821 non-null  str
 4   Element Name       31821 non-null  str
 5   Hot Technology     31821 non-null  str
 6   In Demand          31821 non-null  str
dtypes: str(7)
memory usage: 4.8 MB

In [28]:
print("=== MISSING VALUES (sorted) ===")
missing = df_software.isnull().sum().sort_values(ascending=False)
print(missing[missing > 0] if missing.sum() > 0 else "No missing values found.")
print()
print(f"Total missing values: {df_software.isnull().sum().sum()}")

=== MISSING VALUES (sorted) ===
No missing values found.

Total missing values: 0

In [29]:
print("=== DUPLICATE ROWS ===")
dup_count = df_software.duplicated().sum()
print(f"Duplicate rows: {dup_count}")

=== DUPLICATE ROWS ===
Duplicate rows: 0

In [30]:
print("=== POSSIBLE ID COLUMNS ===")
id_cols = [c for c in df_software.columns if "id" in c.lower() or "code" in c.lower()]
print(f"Columns with 'id' or 'code' in name: {id_cols}")
print()

for col in id_cols:
    unique_count = df_software[col].nunique()
    total = len(df_software)
    status = "(UNIQUE)" if unique_count == total else "(NOT UNIQUE)"
    print(f"  {col}: {unique_count} unique values out of {total} rows {status}")

=== POSSIBLE ID COLUMNS ===
Columns with 'id' or 'code' in name: ['O*NET-SOC Code', 'Element ID']

  O*NET-SOC Code: 923 unique values out of 31821 rows (NOT UNIQUE)
  Element ID: 134 unique values out of 31821 rows (NOT UNIQUE)

In [31]:
print("=== DATA TYPES ===")
print()
num_cols = df_software.select_dtypes(include=[np.number]).columns.tolist()
cat_cols = df_software.select_dtypes(include=["object", "category", "str"]).columns.tolist()

print(f"Numerical columns ({len(num_cols)}):")
for c in num_cols:
    print(f"  - {c}")
print()
print(f"Categorical/text columns ({len(cat_cols)}):")
for c in cat_cols:
    print(f"  - {c}")

=== DATA TYPES ===

Numerical columns (0):

Categorical/text columns (7):
  - O*NET-SOC Code
  - Title
  - Workplace Example
  - Element ID
  - Element Name
  - Hot Technology
  - In Demand

---
## Data Understanding Summary

The table below consolidates what we found in each dataset.
---

In [32]:
# Build summary table from actual data
datasets = {
    "employee_attrition": df_attrition,
    "hr_performance_engagement": df_engagement,
    "occupation_data": df_occupation,
    "essential_skills": df_essential,
    "software_skills": df_software,
}

purposes = {
    "employee_attrition": "Attrition prediction",
    "hr_performance_engagement": "Engagement/performance analytics",
    "occupation_data": "Occupation/role master",
    "essential_skills": "Essential skills required by roles",
    "software_skills": "Software/technology skills required by roles",
}

summary_rows = []
for name, df in datasets.items():
    rows, cols = df.shape
    missing = df.isnull().sum().sum()
    dups = df.duplicated().sum()
    id_candidates = [c for c in df.columns if "id" in c.lower() or "code" in c.lower()]
    id_info = "None found"
    if id_candidates:
        id_info = ", ".join(id_candidates)
    summary_rows.append({
        "Dataset": name,
        "Rows": rows,
        "Columns": cols,
        "Missing Values": int(missing),
        "Duplicate Rows": int(dups),
        "Possible ID": id_info,
        "Purpose": purposes[name],
    })

summary_df = pd.DataFrame(summary_rows)
summary_df

                     Dataset   Rows  Columns  Missing Values  Duplicate Rows                           Possible ID                                       Purpose
0         employee_attrition   1470       35               0               0                            None found                          Attrition prediction
1  hr_performance_engagement   2845       28               0               0               Employee ID, GenderCode              Engagement/performance analytics
2            occupation_data   1016        3               0               0                        O*NET-SOC Code                        Occupation/role master
3           essential_skills  18200       15            9100               0  O*NET-SOC Code, Element ID, Scale ID            Essential skills required by roles
4            software_skills  31821        7               0               0            O*NET-SOC Code, Element ID  Software/technology skills required by roles

---
## Key Findings

### Employee Attrition
- The employee identifier column is **EmployeeNumber** (all values are unique).
- The Attrition column contains "Yes"/"No" values — it's the prediction target.
- `EmployeeCount` and `StandardHours` are constant across all rows — likely not useful for modeling.
- `Over18` is constant ("Y") — not useful.

### HR Performance Engagement
- This dataset uses "Employee ID" as identifier — we need to verify during Step 4 whether it aligns with EmployeeNumber in employee_attrition.
- Contains engagement scores, satisfaction scores, and work-life balance scores.

### Occupation Data
- Uses O*NET-SOC Code as the key — this is a standard occupation classification, not an employee ID.
- Contains role titles and descriptions — serves as a reference/lookup table.

### Essential Skills
- Also uses O*NET-SOC Code — links to occupation_data.
- Contains skill importance and level ratings per occupation.
- This is a many-to-one relationship (many skill rows per occupation).

### Software Skills
- Also uses O*NET-SOC Code — links to occupation_data.
- Contains software/technology tools required per occupation.
- Also many-to-one with occupation_data.

---
**Next step:** Data Validation (02_data_validation.ipynb)